import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 left-0 right-0 h-1 bg-red-600 z-[9999] opacity-50" />
        <div className="fixed top-1 left-2 z-[9999] text-[8px] font-mono text-red-600 bg-white/80 px-1 rounded shadow-sm opacity-50 pointer-events-none">
          DEPLOY: 2026-03-20 03:10 PM
        </div>
        {children}
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
